### ISSUE TITLE
Table Component StyleClassDataprovider

### ISSUE THREAD

**Issue by issBrenda** [Servoy/servoy-extra-components#31]
When adding a StyleClassDataprovider to a column in a Table Component, I receive the following errors in the Servoy Console.  The StyleClassDataprovider is set to a Calculated Field which returns a font icon.

After reviewing with Sean, it looks like it may have to do with this column not being sortable???

These errors are causing some of my other logic not to work:
1.  Highlighted row never gets updated
2.  Right-Click logic doesn't fire

Both of these issues are fixed if I remove the StyleClassDataProvider and go back to using a regular dataprovider.

 > java.lang.NullPointerException
	at com.servoy.j2db.server.ngclient.property.FoundsetLinkedPropertyType.toRhinoValue(FoundsetLinkedPropertyType.java:243)
	at com.servoy.j2db.server.ngclient.property.FoundsetLinkedPropertyType.toRhinoValue(FoundsetLinkedPropertyType.java:1)
	at com.servoy.j2db.server.ngclient.property.types.NGConversions.convertSabloComponentToRhinoValue(NGConversions.java:421)
	at com.servoy.j2db.server.ngclient.component.RhinoMapOrArrayWrapper.get(RhinoMapOrArrayWrapper.java:132)
	at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2141)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1518)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1505)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1408)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:837)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:158)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:406)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3204)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:156)
	at com.servoy.j2db.scripting.ScriptEngine.executeFunction(ScriptEngine.java:664)
	at com.servoy.j2db.debug.RemoteDebugScriptEngine.executeFunction(RemoteDebugScriptEngine.java:393)
	at com.servoy.j2db.BasicFormController.executeFunction(BasicFormController.java:1063)
	at com.servoy.j2db.BasicFormController.executeFormMethod(BasicFormController.java:782)
	at com.servoy.j2db.BasicFormController.executeOnLoadMethod(BasicFormController.java:635)
	at com.servoy.j2db.server.ngclient.NGFormManager.leaseFormPanel(NGFormManager.java:267)
	at com.servoy.j2db.server.ngclient.NGFormManager.getForm(NGFormManager.java:235)
	at com.servoy.j2db.server.ngclient.component.WebFormController.notifyVisible(WebFormController.java:696)
	at com.servoy.j2db.server.ngclient.NGFormServiceHandler.executeMethod(NGFormServiceHandler.java:208)
	at org.sablo.websocket.WebsocketEndpoint$5.run(WebsocketEndpoint.java:323)
	at org.sablo.eventthread.Event$1.run(Event.java:100)
	at org.sablo.websocket.CurrentWindow.runForWindow(CurrentWindow.java:77)
	at org.sablo.eventthread.Event.execute(Event.java:90)
	at org.sablo.eventthread.EventDispatcher.dispatch(EventDispatcher.java:125)
	at org.sablo.eventthread.EventDispatcher.run(EventDispatcher.java:89)
	at com.servoy.j2db.server.ngclient.eventthread.NGEventDispatcher.run(NGEventDispatcher.java:55)
	at java.lang.Thread.run(Unknown Source)

**Comment by costescuandrei** [comment]
This should already be fixed in Servoy 8.2.
