### ISSUE TITLE
angular / uppy error on Version 2022.6.4

### ISSUE THREAD

**Issue by SilvanusLupus** [Servoy/servoy-extra-components#81]
Hi,

we have an error 404 in all our form editors after updating our Servoy Extra Components to 2022.6.4 and our keylistener to 2022.3.1.
Our Servoy Extra Components were on version 2022.6.4 before. 
We updated as soon, as the update was released via SPM.

The Error just appeared, when updating the KeyListener, that's why we created the issue there first.

Also we tried to downgrade reinstall both keylistener and Servoy Extra Components.
We deleted the com.servoy.eclipse.ngclient.ui-folder and forced a new build after every downgrade and every reinstallation.
Nothing worked so far.

Our Servoy is on version 2022.6.0.8782.

I recreated the updates we did on a second PC. There the Error appears when updating the Servoy Extra Components to 2022.6.4 (same Version of Servoy).

I'll add my console output of the Error while building below (windows version)

```
./node_modules/@uppy/angular/fesm2015/uppy-angular.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string 'C:\workspaces_ti\HVO2go\.metadata\.plugins\com.servoy.eclipse.ngclient.ui\target\node_modules\@uppy\angular\fesm2015\uppy-angular.mjs: This application depends upon a library published using Angular version 14.1.3, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
49 | }
50 | DashboardComponent.Éµfac = i0.ÉµÉµngDeclareFactory({ minVersion: "12.0.0", version: "14.1.3", ngImport: i0, type: DashboardComponent, deps: [{ token: i0.ElementRef }], target: i0.ÉµÉµFactoryTarget.Component });
> 51 | DashboardComponent.Éµcmp = i0.ÉµÉµngDeclareComponent({ minVersion: "14.0.0", version: "14.1.3", type: DashboardComponent, selector: "uppy-dashboard", inputs: { uppy: "uppy", props: "props" }, usesInheritance: true, usesOnChanges: true, ngImport: i0, template: '', isInline: true, changeDetection: i0.ChangeDetectionStrategy.OnPush });
|                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
52 | i0.ÉµÉµngDeclareClassMetadata({ minVersion: "12.0.0", version: "14.1.3", ngImport: i0, type: DashboardComponent, decorators: [{
53 |             type: Component,
54 |             args: [{'
at run (C:\workspaces_ti\HVO2go\.metadata\.plugins\com.servoy.eclipse.ngclient.ui\target\node_modules\@babel\core\lib\transformation\index.js:37:15)
at run.next (<anonymous>)
at Function.transform (C:\workspaces_ti\HVO2go\.metadata\.plugins\com.servoy.eclipse.ngclient.ui\target\node_modules\@babel\core\lib\transform.js:25:41)
at transform.next (<anonymous>)
at step (C:\workspaces_ti\HVO2go\.metadata\.plugins\com.servoy.eclipse.ngclient.ui\target\node_modules\gensync\index.js:261:32)
at C:\workspaces_ti\HVO2go\.metadata\.plugins\com.servoy.eclipse.ngclient.ui\target\node_modules\gensync\index.js:273:13
at async.call.result.err.err (C:\workspaces_ti\HVO2go\.metadata\.plugins\com.servoy.eclipse.ngclient.ui\target\node_modules\gensync\index.js:223:11)
at C:\workspaces_ti\HVO2go\.metadata\.plugins\com.servoy.eclipse.ngclient.ui\target\node_modules\gensync\index.js:37:40

Error: node_modules/@uppy/angular/lib/components/dashboard-modal/dashboard-modal.component.d.ts:17:18 - error TS2314: Generic type 'ÉµÉµComponentDeclaration' requires 7 type argument(s).

17     static Éµcmp: i0.ÉµÉµComponentDeclaration<DashboardModalComponent, "uppy-dashboard-modal", never, { "uppy": "uppy"; "props": "props"; "open": "open"; }, {}, never, never, false>;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@uppy/angular/lib/components/dashboard/dashboard.component.d.ts:15:18 - error TS2314: Generic type 'ÉµÉµComponentDeclaration' requires 7 type argument(s).

15     static Éµcmp: i0.ÉµÉµComponentDeclaration<DashboardComponent, "uppy-dashboard", never, { "uppy": "uppy"; "props": "props"; }, {}, never, never, false>;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@uppy/angular/lib/components/drag-drop/drag-drop.component.d.ts:15:18 - error TS2314: Generic type 'ÉµÉµComponentDeclaration' requires 7 type argument(s).

15     static Éµcmp: i0.ÉµÉµComponentDeclaration<DragDropComponent, "uppy-drag-drop", never, { "uppy": "uppy"; "props": "props"; }, {}, never, never, false>;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@uppy/angular/lib/components/progress-bar/progress-bar.component.d.ts:15:18 - error TS2314: Generic type 'ÉµÉµComponentDeclaration' requires 7 type argument(s).

15     static Éµcmp: i0.ÉµÉµComponentDeclaration<ProgressBarComponent, "uppy-progress-bar", never, { "uppy": "uppy"; "props": "props"; }, {}, never, never, false>;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@uppy/angular/lib/components/status-bar/status-bar.component.d.ts:15:18 - error TS2314: Generic type 'ÉµÉµComponentDeclaration' requires 7 type argument(s).

15     static Éµcmp: i0.ÉµÉµComponentDeclaration<StatusBarComponent, "uppy-status-bar", never, { "uppy": "uppy"; "props": "props"; }, {}, never, never, false>;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



Finished running 'run build_debug_nowatch ' time: 29s

Total time to check/install Titanium NG target folder: C:\workspaces_ti\HVO2go\.metadata\.plugins\com.servoy.eclipse.ngclient.ui\target is 113s


```

**Comment by jcompagner** [comment]
With the latest version of servoy extra this should be fixed because it depends on an uppy:

"@uppy/angular": "<0.4",

which fixes this

So you didn't correctly update to that release, you can try to do a "Copy Titanium NGClient sources" -> and then Copy and Clean build to see if that helps

but if you get that error then you are on a wrong servoy extra version that installs uppy 0.4 which is based on angular 14
